### PR TITLE
💬 Chat: add Chat with Us link to top nav and hero area

### PR DESCRIPTION
**Pull request by machikoyasuda**
Changes proposed in this pull request:

* Desktop: Add Chat with Us link to top nav
* Mobile: Add Chat with Us to top middle area, not in the nav

FYI: Users will not be able to start conversations on wanikani.com and continue them on knowledge.wanikani.com.

#### Desktop
image
image
image

#### Mobile
image
image

### Testing
- Test a real conversation with someone in support from the homepage on Desktop
- Test a real conversation with someone in support from the homepage on Mobile
- Test a real conversation with someone in support from a sub-page on Desktop
- Test a real conversation with someone in support from a sub-page on Mobile

---

The credentials to view the Netlify deploy is the following:

* **username**: crabigator
* **password**: googlebegone

### CODE REVIEW

**Comment by vietqhoang** [comment]
Deploy preview for *wanikani-knowledgebase* processing.

Building with commit ead06552acfee24bffb4b3d402f020eced0742e5

https://app.netlify.com/sites/wanikani-knowledgebase/deploys/5f72651b99cc78000789b2e1

**Comment by machikoyasuda** [comment]
image

**Comment by machikoyasuda** [comment]
This is ready for review! 🎉

@michaelrichey - It looks like you had this app running locally recently. Can you get this PR to run locally? I want someone to confirm this - b/c I personally wasn't able to get it running locally in this form ... I was getting a weird Ruby/Bundler bug. But maybe it's just me.

@michaelrichey / @oldbonsai - Does the orange color button look good?

@JenKay - Once a developer has reviewed this PR and approved it, we can do some testing on https://deploy-preview-43--wanikani-knowledgebase.netlify.app/# After that, once we click *merge* on this PR, the changes will be deployed to https://knowledge.wanikani.com/

**Review by michaelrichey — APPROVED** [review]
I tested the chat on Netlify in the four places asked:
- main page desktop
- main page mobile
- sub page desktop
- sub page mobile

Mobile tests were on iPhone SE on Safari.

I could not run repo locally. I got the same bundler/ruby problem Machiko described. The error claimed I was using a version of Ruby that I did not have installed. So I abandoned trying to run it locally after a few tries.

The chat worked in all cases and the orange button looks great. Approved!

**Comment by machikoyasuda** [comment]
@michaelrichey 👀  i see u!

image

**Pull request merged**
